### ISSUE TITLE
Parsing of JSON schema with required properties fails

### ISSUE THREAD

**Issue by benjaminbauer** [adrobisch/raml-converter#13]
I use version 0.12 of the maven plugin during the compile phase of my maven project to convert a raml file to html.

I import following json schema in my raml file:

``` json
{
  "$schema": "http://json-schema.org/schema",
  "type": "object",
  "description": "foo",
  "properties": {
    "toplevel": {
      "type": "object",
      "properties": {
        "subprop": {
          "type": "string"
        }
      },
      "required": [
        "subprop"
      ]
    }
  }
}
```

The conversion fails with the following error:

``` bash
[ERROR] Failed to execute goal de.androbit:raml-converter-maven-plugin:0.12:html (default) on project global_identifier_service: Execution default of goal de.androbit:raml-converter-maven-plugin:0.12:html failed: raml_template:64:19: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.Boolean
[ERROR] raml_template:64:19
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal de.androbit:raml-converter-maven-plugin:0.12:html (default) on project global_identifier_service: Execution default of goal de.androbit:raml-converter-maven-plugin:0.12:html failed: raml_template:64:19: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.Boolean
    raml_template:64:19
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal de.androbit:raml-converter-maven-plugin:0.12:html failed: raml_template:64:19: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.Boolean
    raml_template:64:19
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    ... 20 more
Caused by: com.github.jknack.handlebars.HandlebarsException: raml_template:64:19: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.Boolean
    raml_template:64:19
    at raml.tools.model.SchemaContext.readPropertyDefinitionFromMap(SchemaContext.java:65)
    at raml.tools.model.SchemaContext.readProperties(SchemaContext.java:41)
    at raml.tools.model.SchemaContext.<init>(SchemaContext.java:28)
    at raml.tools.model.RamlContext.getConsolidatedSchemas(RamlContext.java:86)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.github.jknack.handlebars.context.MethodValueResolver.invokeMember(MethodValueResolver.java:51)
    at com.github.jknack.handlebars.context.MethodValueResolver.invokeMember(MethodValueResolver.java:35)
    at com.github.jknack.handlebars.context.MemberValueResolver.resolve(MemberValueResolver.java:75)
    at com.github.jknack.handlebars.Context$CompositeValueResolver.resolve(Context.java:106)
    at com.github.jknack.handlebars.Context.resolve(Context.java:597)
    at com.github.jknack.handlebars.Context.internalGet(Context.java:548)
    at com.github.jknack.handlebars.Context.get(Context.java:470)
    at com.github.jknack.handlebars.internal.ParamType$5.doParse(ParamType.java:108)
    at com.github.jknack.handlebars.internal.ParamType.parse(ParamType.java:155)
    at com.github.jknack.handlebars.internal.HelperResolver.determineContext(HelperResolver.java:119)
    at com.github.jknack.handlebars.internal.Block.merge(Block.java:160)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
    at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:71)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:117)
    at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:101)
    at raml.tools.html.Raml2HtmlRenderer.renderHandlebars(Raml2HtmlRenderer.java:124)
    at raml.tools.html.Raml2HtmlRenderer.renderClassPathTemplate(Raml2HtmlRenderer.java:116)
    at raml.tools.html.Raml2HtmlRenderer.renderFull(Raml2HtmlRenderer.java:33)
    at raml.tools.html.Raml2HtmlConverter.convert(Raml2HtmlConverter.java:25)
    at raml.converter.maven.RamlHtmlMojo.writeHtml(RamlHtmlMojo.java:58)
    at raml.converter.maven.RamlHtmlMojo.execute(RamlHtmlMojo.java:44)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    ... 21 more
Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.Boolean
    ... 52 more
```

I narrowed it down to the `"required":["subprop"]`: When I delete that, the conversion works.

**Comment by adrobisch** [comment]
Hi Benjamin, 
thanks for reporting this! There should be no exception in the new 0.13 release. You should be aware that the template does not iterate embedded object definitions, so you will just see something like `toplevel object required`. I would recommend that you use another schema for the embedded object and just reference it: 

``` javascript
schemas:
  - toplevel: |
      {
        "$schema": "http://json-schema.org/schema",
        "type": "object",
        "description": "foo",
        "properties": {
          "toplevel" : {
            "$ref": "sub"
          }
        }
      }
  - sub: |
      {
        "$schema": "http://json-schema.org/schema",
        "type": "object",
        "description": "sub",
        "properties": {
          "subprop": {
            "type": "string"
          }
        },
        "required" : ["subprop"]
      }
```

You will get the full properties documentation and a link from `toplevel` to the `sub`-schema then.

**Comment by benjaminbauer** [comment]
Hi Andreas,
I have to thank you for the awesome support! Not even did u fix it and release it in 5h after reporting, but you also reviewed my code :)

Viele Grüße nach Berlin!

**Comment by adrobisch** [comment]
;) happy to help.

**Comment by adrobisch** [comment]
It turned out that the previous fix was incomplete, there are different approaches to the required fields in JSON Schema Draft 3 (https://tools.ietf.org/html/draft-zyp-json-schema-03#section-5.7) and Draft 4 (http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.15), so the version needs to be considered for this.
